# Generated by Django 3.2.13 on 2022-07-11 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClerkProfile', '0002_clerkpayroll_clerk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerkpayroll',
            name='clerk',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clerkprofile1', to='ClerkProfile.clerkprofile'),
        ),
    ]
