# Generated by Django 3.1.5 on 2022-08-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('context', models.CharField(max_length=500, verbose_name='评论内容')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='weibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('article', models.CharField(max_length=500, verbose_name='文章')),
                ('likes_num', models.IntegerField(verbose_name='点赞数')),
                ('comment_num', models.IntegerField(verbose_name='评论数')),
                ('transmit_num', models.IntegerField(verbose_name='转发数')),
                ('c_time', models.CharField(max_length=50, verbose_name='最后回复时间')),
                ('pic_links', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片链接')),
                ('art_links', models.CharField(blank=True, max_length=200, null=True, verbose_name='文章链接')),
            ],
            options={
                'verbose_name': '微博帖子',
                'verbose_name_plural': '微博帖子',
            },
        ),
        migrations.CreateModel(
            name='SecondComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('context', models.CharField(max_length=500, verbose_name='评论回复内容')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondcomment', to='yuqing.weibo', verbose_name='评论')),
                ('com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondcomment', to='yuqing.firstcomment', verbose_name='评论')),
            ],
            options={
                'verbose_name': '评论的回复',
                'verbose_name_plural': '评论的回复',
            },
        ),
        migrations.AddField(
            model_name='firstcomment',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstcomment', to='yuqing.weibo', verbose_name='文章'),
        ),
    ]
