# Generated by Django 3.2.13 on 2022-08-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuqing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstcomment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='secondcomment',
            options={'verbose_name': '评论的回复', 'verbose_name_plural': '评论的回复'},
        ),
        migrations.AlterModelOptions(
            name='weibo',
            options={'verbose_name': '微博帖子', 'verbose_name_plural': '微博帖子'},
        ),
    ]
