# Generated by Django 3.1.5 on 2022-08-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yuqing', '0002_auto_20220803_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibo',
            name='art_links',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='文章链接'),
        ),
        migrations.AlterField(
            model_name='firstcomment',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstcomment', to='yuqing.weibo', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='firstcomment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='secondcomment',
            name='com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondcomment', to='yuqing.firstcomment', verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='secondcomment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
