# Generated by Django 3.2.13 on 2022-07-02 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_telephone', models.CharField(blank=True, max_length=50, verbose_name='联系方式')),
                ('pet_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='宠物姓名')),
                ('pet_age', models.SmallIntegerField(verbose_name='宠物年龄')),
                ('pet_id', models.IntegerField(unique=True, verbose_name='宠物编号')),
                ('pet_breed', models.CharField(blank=True, max_length=50, verbose_name='宠物种类')),
                ('pet_gender', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=50, verbose_name='宠物性别')),
                ('pet_physical_date', models.DateTimeField(auto_now=True, verbose_name='最后体检时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet Profile',
            },
        ),
    ]
