# Generated by Django 3.2.13 on 2022-07-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='pet_age',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='宠物年龄'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_breed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='宠物种类'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=50, null=True, verbose_name='宠物性别'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='宠物编号'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_physical_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后体检时间'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='user_telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='联系方式'),
        ),
    ]
