# Generated by Django 3.2.13 on 2022-07-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petprofile',
            name='pet_physical_date',
        ),
        migrations.AddField(
            model_name='petprofile',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='问诊时间'),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='is_handle',
            field=models.CharField(blank=True, choices=[('未处理', '未处理'), ('已同意', '已同意'), ('已拒绝', '已拒绝')], default='未处理', max_length=20, null=True, verbose_name='处理状态'),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='last_editor',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='最后处理者'),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='pet_illness',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='宠物病情'),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='reply',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='医生意见'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_age',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='宠物年龄'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_breed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='宠物种类'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_gender',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=50, null=True, verbose_name='宠物性别'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='宠物身份证号'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='user_telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='联系方式'),
        ),
    ]
