# Generated by Django 3.2.13 on 2022-07-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetProfile', '0002_auto_20220706_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportPetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_file', models.FileField(upload_to='upload/', verbose_name='上传文件')),
                ('handle_text', models.TextField(blank=True, null=True, verbose_name='处理信息')),
            ],
            options={
                'verbose_name': '批量导入信息',
                'verbose_name_plural': '批量导入信息',
            },
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='is_handle',
            field=models.CharField(blank=True, choices=[('未处理', '未处理'), ('已处理', '已处理'), ('已拒绝', '已拒绝')], default='未处理', max_length=20, null=True, verbose_name='处理状态'),
        ),
    ]
